# LKS 2025 – Global Variables

domain: itnsa.id
password: "Skills39!"

# IP Addresses
ip_int_srv:   "10.10.10.10"
ip_mail:      "10.10.20.10"
ip_web01:     "10.10.20.21"
ip_web02:     "10.10.20.22"
ip_fw_int:    "10.10.10.254"
ip_fw_dmz:    "10.10.20.254"
ip_vrrp:      "10.10.20.100"
ip_budi_clt:  "100.100.100.100"

# WireGuard tunnel (10.10.30.0/24)
wg_server_ip: "10.10.30.1"
wg_client_ip: "10.10.30.2"
wg_port: 51820

# CA paths
ca_dir: /opt/grading/ca
